cart/urls.py
from django.urls import path
from cart.views import (
    cart_home,
    cart_update,
    Cart,
    checkoutHome,
    success,
    cart_api_update
)

# If you are using namespace in main url in include then providing this app_name is necessary
app_name = 'cart'
urlpatterns = [

    path('', cart_home, name='home'),
    path('update', cart_update, name='update'),
    path('checkout', checkoutHome, name='checkout'),
    path('success', success, name='success'),
    # path('api', cart_api_update, name='api'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import home_page, contact_page
from accounts.views import login_Page, registerPage, guest_login_view
from addresses.views import checkout_address_create_view,checkout_address_use_view
from cart.views import cart_api_update
from django.contrib.auth.views import LogoutView

urlpatterns = [
    # here this name is important  during navigation, we don't have to type that url
    path('', home_page, name='home'),
    # we simply have to recall this given name
    path('contact/', contact_page, name='contact'),
    path('checkout/address/create_view/',checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/use_view/',checkout_address_use_view, name='checkout_address_use'),

    path('login/', login_Page, name="login"),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/', registerPage, name="register"),
    path('register/guest/', guest_login_view, name="guest_register"),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace="products")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('cart/api/', cart_api_update, name=''),
    path('search/', include('search.urls', namespace="search")),
]

if settings.DEBUG:
    # set static files
    # print(settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # type python manage.py collectstatic

cart/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed
from decimal import Decimal
User = settings.AUTH_USER_MODEL


# Create your models here.
class CartManager(models.Manager):
    # def get_or_create():
    #     return obj,True
    def new(self, user=None):
        user_obj = None
        if user is not None and user.is_authenticated:
            user_obj = user

        return self.model.objects.create(user=user_obj)

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)  # getting session cart id
        qs = self.get_queryset().filter(id=cart_id)  # getting all objects form the Cart

        if qs.count() == 1:  # here it means user just adding cart for the first time
            new_obj = False  # as because not new cart object got
            cart_obj = qs.first()  # fetching only first object
            # print(request.user.is_authenticated == True)
            if request.user.is_authenticated and cart_obj.user is None:  # for the first time entry for that user

                cart_obj.user = request.user  # adding that user in cart object
                cart_obj.save()  # saveing all details in cart object
        else:
            cart_obj = Cart.objects.new(
                user=request.user)  # creating new object with according user who already logged in and has many product in the cart
            new_obj = True  # yes it new objectConnection
            # if user.is_authenticated:
            #     user_obj = user
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    sub_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action in ['post_add', 'post_remove', 'post_clear']:

        products = instance.products.all()  # fetching all products from cart object in product model

        total = 0
        for x in products:
            total += x.price

        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()


# m2m_changed is a signal used save while using many 2 many connection field setup
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    # print(action)
    gst = 10
    if instance.sub_total > 0:
        instance.total = Decimal(instance.sub_total) + Decimal(gst)
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from accounts.forms import LoginForm, GuestForm
from .models import Cart, Product
from orders.models import Order
from billing.models import Billing
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address


def cart_api_update(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{"name": x.name, "price": x.price}
                for x in cart_obj.products.all()]
    cart_data = {'products': products,
                 "sub_total": cart_obj.sub_total, "total": cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    # because we have two objects coming back
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    return render(request, 'cart/home.html', {'cart': cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    # print(product_id)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Error! Product Gone")
        # print(product_obj)
        # because we have two objects coming back
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        #
        cart_obj.products.all()
        product_added = False
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            product_added = False

        else:
            cart_obj.products.add(product_obj)
            # cart_obj.products.all()
            product_added = True
        # print(cart_obj.products.all())
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax():
            json_data = {
                'added': product_added,
                'removed': not product_added,
                '_count': cart_obj.products.count(),
                'api': 'api/'
            }
            return JsonResponse(json_data , status =200)
            # return JsonResponse({"message":"Error 400"} , status_code=500)
            # print('\noh my fuck! Its ajax')
    return redirect('cart:home')


def checkoutHome(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count == 0:
        return redirect('cart:home')
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    # billing_address_form = AddressForm()
    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)
    billing_profile, billing_profile_created = Billing.objects.new_or_get(
        request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(
                billing_profile=billing_profile)
        #
        # shipping_addres_qs = address_qs.filter(address_type='shipping')
        # billing_addres_qs = address_qs.filter(address_type='billing')
        # address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(
                id=shipping_address_id)
            del(request.session['shipping_address_id'])
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(
                id=billing_address_id)
            del(request.session['billing_address_id'])
        if billing_address_id or shipping_address_id:
            order_obj.save()
    if request.method == 'POST':

        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            del(request.session['cart_id'])
            request.session['cart_items'] = 0
        return redirect('cart:success')

        # pass
    # print(address_qs)
    context = {
        "order": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs
        # "billing_address_form": billing_address_form,
    }
    # print(context)
    return render(request, 'cart/checkOut.html', context)


def success(request):
    return redirect('home')
    # pass

templates/cart/checkOut.html
{% extends 'base.html' %}
{% block content %}
{% if not billing_profile %}
<div class="row row-text-center text-center">
    <div class="col-md-12">
        <div class="row">
            <div class=" col-md-6">
                <p class="lead"> <strong>Login</strong></p>
                {% include 'accounts/snippets/form.html' with form=login_form next_uri=request.build_absolute_uri %}
            </div>
            <div class=" col-md-6">
                <p class="lead"><small>or continue as</small> <strong>Guest</strong></p>
                {% url "guest_register" as guest_register_url %}
                {% include 'accounts/snippets/form.html' with form=guest_form next_uri=request.build_absolute_uri action_url=guest_register_url%}
            </div>
        </div>
    </div>
</div>
{% else %}
{% if not order.shipping_address %}
<div class="row">
    <div class="col-sm-12 ">
        <p class="lead text-center">Shipping Address</p>
    </div>
<div class="col-md-6">
{% url "checkout_address_create" as checkout_create %}

{% include 'addresses/snippets/form.html' with form=address_form next_uri=request.build_absolute_uri action_url=checkout_create address_type='shipping'%}
</div>
{% url "checkout_address_use" as checkout_address_use %}
{# <p>{{checkout_address_use}}</p> #}
{% include 'addresses/snippets/prev_addresses.html' with address_qs=address_qs address_type='shipping' next_uri=request.build_absolute_uri action_url=checkout_address_use %}
</div>

{%elif not order.billing_address%}
<div class="row">
    {{order.order_id}}-- {{ order.cart}}
    <div class="col-sm-12 "><p class="lead "><center>Billing Address</center>  </p></div>
    <div class="col-sm-6 ">
        {% url "checkout_address_create" as checkout_create %}
        {% url "checkout_address_use" as checkout_use %}
        {% include 'addresses/snippets/form.html' with form=address_form next_uri=request.build_absolute_uri action_url=checkout_create address_type='billing'  %}
    </div>
    {% include 'addresses/snippets/prev_addresses.html' with address_qs=address_qs address_type='billing' next_uri=request.build_absolute_uri action_url=checkout_use%}
</div>
{% else %}

{% include 'cart/bootstrap/checkout.html' with order=order%}

{%endif %}
{% endif %}
{% endblock content %}

templates/cart/home.html
{% extends 'base.html' %}
{% block content %}

{% if cart.products.exists %}



<h1>Cart</h1>
  <table class="table cart-table">
      <thead>
          <tr>
              <td scope="row">#</td>
              <td>Product</td>
              <td>Price</td>
          </tr>
      </thead>
      <tbody class="cart-body">
          {% for product in cart.products.all %}
          <tr>
            <td scope="row">
                {{forloop.counter}}
            </td>

            <td>
                <a href="{{product.get_absolute_url}}" >{{product.name}}</a>
                <small>{% include "products/snippests/update-cart.html" with product=product cart=cart %}</small>
            </td>

            <td>
                {{product.price}}
            </td>
        </tr>
          {% endfor %}

          <tr>


            <td colspan="2">
                <b> Sub Total </b>
            </td>

            <td class="cart_sub_total">
                {{cart.sub_total}}
            </td>
        </tr>
        <tr>


            <td colspan="2">
                <b> Total </b>
            </td>

            <td >

                <a class="btn btn-block btn-success cart_total" href=" {% url 'cart:checkout'  %}">Checkout ({{cart.total}} /-)</a>
            </td>
        </tr>
      </tbody>
  </table>
  {% else %}
  <h1>Product doesn't exists</h1>
  {% endif %}
  {% endblock content %}